#!/usr/bin/env python3

import sys
import os

tools_dir = '/home/brylant/Development/Tools'
tools = {
  'jdk': {
    '1.7': 'jdk1.7',
    '1.8': 'jdk1.8'
  }
}

def validateInput():
  if len(sys.argv) == 1:
    print('no arguments given')
    sys.exit(1)

def pathExistsButIsNotSymbolicLink(path):
  return 

def validatePaths(linkPath, toolPath):
  if os.path.exists(linkPath) and not os.path.islink(linkPath):
    print('ERROR: path {} exists but is not a symbolic link'.format(linkPath))
    sys.exit(1)
  if not os.path.exists(toolPath):
    print('ERROR: directory {} does not exist'.format(toolPath))
    sys.exit(1)
  elif not os.path.isdir(toolPath):
    print('ERROR: path {} exists but is not a directory'.format(toolPath))
    sys.exit(1)

if __name__ == "__main__":
  validateInput()
  tool = sys.argv[1]
  version = sys.argv[2]
  linkPath = tools_dir + '/' + tool
  toolPath = tools_dir + '/' + tools[tool][version]
  validatePaths(linkPath, toolPath)
  
  if os.path.exists(linkPath):
    os.remove(linkPath)
  os.symlink(toolPath, linkPath)
